<Project Sdk="Meadow.Sdk/1.1.0">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12.0</LangVersion>
    <AssemblyName>Meadow.RTLiteForMicrocontrollers</AssemblyName>
    <Company>Wilderness Labs, Inc</Company>
    <PackageProjectUrl>http://developer.wildernesslabs.co/Meadow/</PackageProjectUrl>
    <PackageId>Meadow.Foundation.RTLiteForMicrocontrollers</PackageId>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/WildernessLabs/Meadow.TensorFlow</RepositoryUrl>
    <PackageTags>Meadow,Tensor,Flow,TensorFlow,RTLite,Machine,Learning,ML,AI,artificial,intelligence,edge,microcontroller,microcontrollers</PackageTags>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Meadow.Foundation.RTLite</RootNamespace>
    <Nullable>enable</Nullable>
    <Description>RTLite for Microcontrollers for use with Wilderness Labs Meadow</Description>
    <Authors>Wilderness Labs, Inc</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <None Include=".\Readme.md" Pack="true" PackagePath="" />
    <None Include="icon.png" Pack="true" PackagePath="" />
    <None Include="Readme.md" Pack="true" PackagePath="" />
	<Content Include="..\..\TensorFlow\TensorFlow.so" Pack="true" PackageCopyToOutput="true">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</Content>
  </ItemGroup>
</Project>
