<Project Sdk="Meadow.Sdk/1.1.0">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <OutputType>Library</OutputType>
        <AssemblyName>App</AssemblyName>
        <LangVersion>10.0</LangVersion>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="Models\**" />
      <Compile Remove="TestData\**" />
      <EmbeddedResource Remove="Models\**" />
      <EmbeddedResource Remove="TestData\**" />
      <None Remove="Models\**" />
      <None Remove="TestData\**" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Meadow.Core\source\implementations\f7\Meadow.F7\Meadow.F7.csproj" />
        <ProjectReference Include="..\..\..\..\Meadow.Core\source\Meadow.Core\Meadow.Core.csproj" />
        <ProjectReference Include="..\..\..\..\Meadow.ProjectLab\Source\Meadow.ProjectLab\Meadow.ProjectLab.csproj" />
        <ProjectReference Include="..\..\Driver\Meadow.Foundation.RTLite.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Update="0.bmp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="2.bmp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="app.build.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="mnist.quantized.tflite">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>
      <None Update="4.bmp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="6.bmp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="mnist.tflite">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="no_person.bmp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="person.bmp">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="person_detect.tflite">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>